- name: Update hostname
  become: yes
  ansible.builtin.hostname:
    name: "name-surename-lab2"

- name: Update /etc/hosts
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '127.0.1.1'
    line: '127.0.1.1 name-surename-lab2'

