// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.donation.eoy.version.viewed", 5);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1726772188);
user_pref("app.update.lastUpdateTime.region-update-timer", 1726772188);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1726772188);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1726772218);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1726772188);
user_pref("browser.region.update.updated", 1726772189);
user_pref("browser.search.region", "UA");
user_pref("calendar.caldav.googleResync", 1726772159);
user_pref("calendar.list.sortOrder", "91d80e08-c801-46ca-b9c9-67d6a80e52d8");
user_pref("calendar.registry.91d80e08-c801-46ca-b9c9-67d6a80e52d8.calendar-main-default", true);
user_pref("calendar.registry.91d80e08-c801-46ca-b9c9-67d6a80e52d8.calendar-main-in-composite", true);
user_pref("calendar.registry.91d80e08-c801-46ca-b9c9-67d6a80e52d8.disabled", true);
user_pref("calendar.registry.91d80e08-c801-46ca-b9c9-67d6a80e52d8.name", "Home");
user_pref("calendar.registry.91d80e08-c801-46ca-b9c9-67d6a80e52d8.type", "storage");
user_pref("calendar.registry.91d80e08-c801-46ca-b9c9-67d6a80e52d8.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Europe/Kyiv");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1726772169273");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1726772188);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20240903191356");
user_pref("extensions.lastAppVersion", "115.15.0");
user_pref("extensions.lastPlatformVersion", "115.15.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"9c2c6e29-4bdc-4faa-99a3-e6ee8beb2498\",\"google@search.mozilla.org\":\"41c6efe3-9982-4452-8314-8aa3fc28f7ff\",\"ddg@search.mozilla.org\":\"02acb3ed-aa10-47be-8f80-be0e3954ebce\",\"amazondotcom@search.mozilla.org\":\"eee5712f-19b2-4326-96d8-9f56c1075703\",\"wikipedia@search.mozilla.org\":\"9229a98b-d339-4aa0-acc4-4d19f3528366\",\"bing@search.mozilla.org\":\"cf04ba0e-7191-430b-a3de-074b47405646\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1726772345);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 40);
user_pref("mailnews.database.global.datastore.id", "7582c8dc-d599-4d10-a490-7602307fba8");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "115.15.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1726772345);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("services.settings.clock_skew_seconds", -11607);
user_pref("services.settings.last_etag", "\"1648185887941\"");
user_pref("services.settings.last_update_seconds", 1726783795);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1726783795);
user_pref("services.settings.thunderbird.search-config.last_check", 1726783795);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1726783795);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1726772345);
user_pref("toolkit.startup.last_success", 1726776700);
user_pref("toolkit.telemetry.cachedClientID", "c27d669b-1b43-41b2-8bde-9b8c6a9df519");
user_pref("toolkit.telemetry.previousBuildID", "20240903191356");
